### ISSUE TITLE
Pivot Field not loading a collection of pivot items

### ISSUE THREAD

**Issue by safiness** [OfficeDev/office-js-docs-reference#1033] opened 2021-09-04 01:25 UTC
# Provide required information needed to triage your issue

## Your Environment

Not relevant
 
## Expected behavior
The items of a pivot field should represent a collection of PivotItems.

## Current behavior
The items of a pivot field represent the collection of pivotfields that the pivotfield came from.

# Provide additional details
The documentation seems a bit off, it is not clear on the expected output, as the description and output definitions are different. Please check: https://docs.microsoft.com/en-us/javascript/api/excel/excel.pivotfield?view=excel-js-preview#items

![image](https://user-images.githubusercontent.com/72071423/132077843-d985698d-3e00-415e-b67f-2bbb2d2a5ef6.png)

**Comment by alison-mk** [comment] 2021-09-08 18:23
Hi @safiness, thank you for submitting this issue! I will update the documentation for the PivotField items property and close this issue once that change is merged. 

Cheers, 
Alison

**Comment by safiness** [comment] 2021-09-08 21:21
Hi @alison-mk, 

Can you clarify and check that the items of a pivot field do return a collection of pivot items.

I seem to be experiencing what the documentation suggests, which is 
"The items of a pivot field represent the collection of pivotfields that the pivotfield came from"

If the latter is implemented it makes it pretty difficult to get to the pivot items of any pivot field, as you would have to know them by name or id, and had no way to find out what these were.

Cheers, 
Sanjay

**Comment by alison-mk** [comment] 2021-09-08 23:34
Hi @safiness, 

Yes, I tested today and confirmed that a PivotField returns a PivotItemCollection which contain multiple PivotItems. Our conceptual documentation article on PivotTables describes the [PivotTable object model](https://docs.microsoft.com/office/dev/add-ins/excel/excel-add-ins-pivottables#object-model). I'm not finding any bugs in the product. I think the bug is in our documentation. I'm sorry that this is causing confusion! 

Alison

**Comment by safiness** [comment] 2021-09-12 10:29
@alison-mk  Thanks for the pointers!

**Comment by AlexJerabek** [comment] 2021-09-13 16:46
Looks like this issue was not closed when https://github.com/OfficeDev/office-js-docs-reference/pull/1035 was checked in. I'm going to close the issue. @safiness, please let us know if you have any further questions about PivotTables.

**Closed by AlexJerabek** 2021-09-13 16:46 UTC
Labels: Type: doc bug
