### ISSUE TITLE
insertField type macrobutton giving error

### ISSUE THREAD

**Issue by TypefiRPerera** [OfficeDev/office-js-docs-reference#1712] opened 2023-10-12 16:12 UTC
async function rangeInsertMacro() {
  try {
    await Word.run(async (context) => {
      var range = context.document.getSelection().getRange();

      const field = range.insertField(Word.InsertLocation.end, Word.FieldType.macroButton);

      field.load("result,code");
      await context.sync();

      if (field.isNullObject) {
        console.log("There are no fields in this document.");
      } else {
        console.log("Code of the field: " + field.code);
        console.log("Result of the field: " + JSON.stringify(field.result));
      }
    });
  } catch (error) {
    if (error instanceof OfficeExtension.Error) {
      console.log("Debug info: " + error.debugInfo);
    } else {
      console.log("An error occurred: " + error);
    }
  }
}

after executing above code in Script Lab, I ended up with following error.

Debug info: {"code":"InvalidArgument","message":"The argument you provided is not valid. Check the OfficeExtension.Error.debugInfo for more information.","errorLocation":"Range.insertField","statement":"var insertField = range.insertField(...);","surroundingStatements":["var root = context.root;","var selection = root.getSelection();","// Instantiate {selection}","var range = selection.getRange();","// Instantiate {range}","// >>>>>","var insertField = range.insertField(...);","// <<<<<","// Instantiate {insertField}"],"fullStatements":["Please enable config.extendedErrorLogging to see full statements."]}

**Comment by AlexJerabek** [comment] 2023-10-12 16:54
Hi @TypefiRPerera,

Thanks for reaching out. @ElizabethSamuel-MSFT, could you please investigate. Offhand, I'm guessing that macro buttons can't be inserted through add-ins.

**Comment by TypefiRPerera** [comment] 2023-10-12 18:09
@ElizabethSamuel-MSFT it's working fine with Desktop version of Word365. I'm getting this error in the Webapp of Word365.

**Comment by ElizabethSamuel-MSFT** [comment] 2023-10-12 18:43
@TypefiRPerera Thanks for providing that information. At present, the web version of the Word UI doesn't support inserting Fields - only Word on Windows and on Mac support this feature per products listed at the top of the support.microsoft.com article [Insert, edit, and view fields in Word](https://support.microsoft.com/office/c429bbb0-8669-48a7-bd24-bab6ba6b06bb). Any fields already in the document are read only. As such, the API can't insert fields into the web version.

I'll go ahead and close this as By Design.

Thanks and we appreciate your interest in Office Add-ins.

**Closed by ElizabethSamuel-MSFT** 2023-10-12 18:43 UTC
Labels: Area: Word, Resolution: by design

**Comment by TypefiRPerera** [comment] 2023-10-13 05:42
@ElizabethSamuel-MSFT  We will looking forward for this feature in the webapp also. We hardly use Word.Fields and Macrobuttons. Highly appreciate a positive feedback.

Thank you,

**Comment by ElizabethSamuel-MSFT** [comment] 2023-10-19 14:56
@TypefiRPerera We're updating the documentation to clarify this (see [this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67089)). There are a few fields that *can* be inserted (and maybe edited) using the API in Word on the web. Unfortunately, that list doesn't include the MacroButton type at present.
