### ISSUE TITLE
Using thisDocument.save(); gives "compatibility mode" as document file name. There is no option to give filename

### ISSUE THREAD

**Issue by rajha-conga** [OfficeDev/office-js-docs-reference#764] opened 2020-08-13 03:58 UTC
Using thisDocument.save(); gives "compatibility mode" as document file name. 
Is there any option to give document filename or do SaveAs() ?
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd71647a-75de-038e-536a-7e56dd48ef3c
* Version Independent ID: a8bc56eb-0948-1ae0-0654-6b751ee9435f
* Content: [Word.Document class - Office Add-ins](https://docs.microsoft.com/en-gb/javascript/api/word/word.document?redirectedfrom=MSDN&view=word-js-preview#save--)
* Content Source: [docs/docs-ref-autogen/word/word/word.document.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.document.yml)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment] 2020-08-13 16:26
Hi @rajha-conga, 

Thank you for reporting this.

There is no current JavaScript API for naming a file when saving. I'd recommend heading over to [UserVoice](https://officespdev.uservoice.com/) and requesting the feature. We use UserVoice to help prioritize feature requests based on the community's votes. As a workaround, you could use the Common API's [Document.getFileAsync](https://docs.microsoft.com/en-gb/javascript/api/office/office.document?view=word-js-preview#getfileasync-filetype--callback-) to get the contents of the Word doc and use other JS file APIs to save the file with a different name.

As for "compatibility mode" being the file name, that sounds like a bug. Could you please open an issue in the [office-js repo](https://github.com/OfficeDev/office-js)? That repo tracks issues with the Office JavaScript APIs. Please include your build of Word, screenshots of the issue, and if possible, a [Script Lab](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/explore-with-script-lab) snippet that reproduces the issue (I could not reproduce this behavior on my machine).

I'm going to close this issue, since there nothing actionable to do in the documentation. Please reply to this thread (or create a new issue) if there's any other issues or you need help with the follow-up items. Thanks!

**Closed by AlexJerabek** 2020-08-13 16:26 UTC
Labels: Needs: triage :mag:

**Comment by rajha-conga** [comment] 2020-08-14 08:27
Thanks @AlexJerabek for your response. Sure, I will raise a ticket for compatibility mode.
