### ISSUE TITLE
Excel refresh all API is not descriptive

### ISSUE THREAD

**Issue by sumurthy** [OfficeDev/office-js-docs-reference#805] opened 2020-09-30 17:12 UTC
## Article URL
https://docs.microsoft.com/en-us/javascript/api/excel/excel.dataconnectioncollection?view=excel-js-preview

## Issue
The refreshAll API simply says - Refreshes all the Data Connections in the collection.

However, it doesn't support linked data types, Power Query, etc. It'd be good to document what we actually support and don't.

**Comment by sumurthy** [comment] 2020-10-04 18:36
Example of scenario where detailed description would help out -- https://stackoverflow.com/questions/64184867/refresh-all-queries-and-connections-of-an-excel-workbook-excel-online-using-of

**Comment by alison-mk** [comment] 2022-06-10 18:44
Closing issue as this request has been tracked in an internal backlog. Fix will be available to public soon.

**Closed by alison-mk** 2022-06-10 18:44 UTC
Labels: Area: Excel, Type: doc request, Status: fix pending

**Comment by md-5** [comment] 2023-11-08 23:55
Still not fixed.

**Comment by AlexJerabek** [comment] 2023-11-09 00:00
Hi @md-5,

The current `refreshAll` description reads:

>Refreshes data connections in the collection, such as from a PivotTable to a Power BI dataset, or a Data Model to a table or range in the same workbook. Data connections unsupported by this method are: Power Query connections, data connections outside the original workbook (except Power BI connections), and connections to data protected by a firewall.

Is there missing or inaccurate information there? Could you please describe the scenario you're not seeing?

**Comment by md-5** [comment] 2023-11-09 00:26
Hi Alex

Thanks for the quick reply.

I'm not seeing stock prices update, which I think falls under the "linked data types" of the original ticket.

**Comment by AlexJerabek** [comment] 2023-11-09 16:51
Thank you for that quick reply. I _think_ the stock prices are a "linked data type". In the short-term, could you try using [LinkedDataTypeCollection.requestRefereshAll](https://learn.microsoft.com/en-us/javascript/api/excel/excel.linkeddatatypecollection?view=excel-js-preview#excel-excel-linkeddatatypecollection-requestrefreshall-member(1)).

The larger issue might just be a bug, since the stock prices were introduced later than the other features mentioned. The current description seems like it encompasses data types. (@alison-mk to confirm I'm not misunderstanding something here). Could you please open a new bug in the [office-js repo](https://github.com/OfficeDev/office-js) that details the expected behavior? That way, it'll get routed to the right folks without the baggage from this issue's previous comments.

**Comment by md-5** [comment] 2023-11-09 21:02
Thanks Alex. The LinkedDataType API looks like what I'm after, but unfortunately it's a preview API so I can't use it in my corporate environment (no insider access, which seems to be required). I'll look at creating a new ticket and also see if I can get a later Excel version somewhere else.

**Comment by AlexJerabek** [comment] 2023-11-09 21:09
Wait, are you calling this API from an Office Script, and not an Office Add-in? If so, that's a known scripting issue: https://learn.microsoft.com/en-us/office/dev/scripts/testing/power-automate-troubleshooting#refresh-not-fully-supported-in-power-automate. Please file a ticket or submit feedback through Excel explaining your need for that functionality and that'll help influence the priority of getting that support.

**Comment by md-5** [comment] 2023-11-10 02:18
Will do, thanks again Alex.
