### ISSUE TITLE
TypeScript type definitions for Office.UI.addHandlerAsync method

### ISSUE THREAD

**Issue by clavx** [OfficeDev/office-js-docs-reference#1096] opened 2021-11-18 08:46 UTC
`Office.AsyncContextOptions` is optional, so I think the following type definition is missing.

Defined
``` typescript
addHandlerAsync(eventType: Office.EventType, handler: (result: DialogParentMessageReceivedEventArgs) => void, options?: Office.AsyncContextOptions, callback?: (result: AsyncResult<void>) => void): void;
```

Undefined
``` typescript
addHandlerAsync(eventType: Office.EventType, handler: (result: DialogParentMessageReceivedEventArgs) => void, callback?: (result: AsyncResult<void>) => void): void;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df1fde12-982a-2f60-54ca-375968a29f33
* Version Independent ID: 7ed56398-e6be-f624-f76d-8982c36fa81a
* Content: [Office.UI interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.ui?view=common-js)
* Content Source: [docs/docs-ref-autogen/office/office/office.ui.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/office.ui.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment] 2021-11-18 17:29
@clavx Thanks for raising this issue. We'll take a look.

**Comment by Rick-Kirkham** [comment] 2021-11-18 21:14
@clavx Please clarify what the issue is. Have you encountered an issue calling the addHandlerAsync method? If so, can you specify what goes wrong?

**Comment by clavx** [comment] 2021-11-19 09:27
Sorry for the lack of explanation.

This is talking about the TypeScript type definitions in `@types/office-js`.

There are two definitions for `displayDialogAsync`, as shown in the [API reference](https://docs.microsoft.com/en-us/javascript/api/office/office.ui?view=common-js).
However, for `addHandlerAsync`, there is only one definition.

The code is quoted from the [document](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#handle-dialogparentmessagereceived-in-the-dialog-box).

``` javascript
Office.onReady()
    .then(function() {
        Office.context.ui.addHandlerAsync(
            Office.EventType.DialogParentMessageReceived,
            onMessageFromParent,
            onRegisterMessageComplete);
    });

function onRegisterMessageComplete(asyncResult) {
    if (asyncResult.status !== Office.AsyncResultStatus.Succeeded) {
        reportError(asyncResult.error.message);
    }
}
```

I thought it should also be included in the TypeScript type definitions in `@types/office-js` so that this can be defined.

![typescript_error](https://user-images.githubusercontent.com/58804032/142597451-191971a1-496b-41d0-873f-4f1249583bed.png)

Thanks.

**Comment by Rick-Kirkham** [comment] 2021-11-19 19:11
Thanks for pointing this out. This is fixed in the source d.ts file now.

**Closed by Rick-Kirkham** 2021-11-19 19:11 UTC
Labels: Area: add-in UI, Type: doc bug, Needs: attention :wave:
